services:
  - type: web
    name: dusa-films
    env: python
    plan: free

    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput

    startCommand: gunicorn dusa.wsgi:application

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dusa-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
