services:
  - type: web
    name: dusa-films
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: |
      python manage.py migrate &&
      gunicorn dusa.wsgi:application
